config/routes.rb
Rails.application.routes.draw do
  resources :videos do
    member do
      post 'view'
    end
  end

  resources :badges

  resources :users

  resources :companies

  get '/log_in/:id' => 'application#log_in', as: :log_in
  get '/log_out' => 'application#log_out', as: :log_out

end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :video_users
  has_many :users, through: :video_users
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # POST /videos/1/view
  def view
    @video = Video.where(:id => view_params).first
    current_user.try :watch_video, @video

    respond_to do |format|
      if current_user.save
        format.html { render :show }
        format.json { render :show, status: :success }
      else
        format.html { render :show }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end

  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title)
    end

    # shouldn't have been necessary, not used in update, but paranoid so will use
    def view_params
      params.require(:id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <% if current_user %>
        <th>Watched?</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <% if current_user %>
          <td><%= current_user.watched? video %></td>
        <% end %>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<script>
// purely as a scratch attempt ... would need to write html for the views count
// ... left as exercise for another time
$(document).ready(function(){

  $('#play_video')
    .bind("ajax:success", function(evt, data, status, xhr){

      // Insert response partial into page below the form.
      $('#watched_value').text("true");
      // then update the views count ...
    })
})

</script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<% if current_user %>
  <p>
    <strong>Watched?:</strong>
    <text id="watched_value">
    <%= current_user.watched? @video %>
    </text>
  </p>
  <% if current_user.watched? @video %>
    <p>
      <strong>Views:</strong>
      <%= current_user.times_watched @video %>
    </p>
  <% end %>

<% end %>

<%= link_to 'Play', view_video_path(@video), {:method => :post, :remote => true, :id => "play_video"} %> |
<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>